language: node_js
node_js:
  - "10"

before_script:
  - npm install -g ganache-cli
  - npm install -g truffle@5.0.4
  - npm install -g solc@0.5.0

script:
  - npm install dotenv
  - npm install truffle-hdwallet-provider
  - ganache-cli --port 8545 -a 3 -e 100 &
  - sleep 5
  - truffle test
